[summarizer]
kind = "ollama"          # "basic" | "ollama" | "openai" (we wired basic+ollama now)
model = "deepseek-r1:7b"
num_ctx = 8192           # larger context if you need big READMEs

[prompt]
# Optional external template to keep style editable without code changes.
# Use placeholders: {repo_name}, {description}, {text}
template_file = "prompts/protfolio_summary2.txt"
version = "v1"           # bump when you change prompt style

[cache]
dir = ".cache"           # future step (we can add file cache keyed by README sha)

[github]
include_forks = false
include_archived = false